version: '3'

services:
  web:
    restart: always
    build: web
    command: /usr/local/bin/gunicorn conf.wsgi -w 2 -b :8000
    volumes:
      - web-django:/app/
      - web-static:/app/static/
    depends_on:
      - postgres

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static/
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:12.17-alpine3.19
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo

volumes:
  web-django:
  web-static:
  pgdata: